export default {
  'GET /v1/backup': {
    type: 'collection',
    data: [
      {
        id: 'BackupID1',
        snapshot: 'Snapshot1',
        timestamp: '11:06AM 3/24/2017',
        size: '500GB',
        created: '4:10PM 3/14/17',
      },
      {
        id: 'BackupID2',
        snapshot: 'Snapshot2',
        timestamp: '11:06AM 3/24/2017',
        size: '500GB',
        created: '4:10PM 3/14/17',
      },
      {
        id: 'BackupID3',
        snapshot: 'Snapshot3',
        timestamp: '11:06AM 3/24/2017',
        size: '500GB',
        created: '4:10PM 3/14/17',
      },
      {
        id: 'BackupID4',
        snapshot: 'Snapshot4',
        timestamp: '11:06AM 3/24/2017',
        size: '500GB',
        created: '4:10PM 3/14/17',
      },
    ],
  },
  'GET /v1/host': {
    type: 'collection',
    data: [
      {
        id: 1,
        state: 'Activated',
        name: 'HostnameOne',
        ip: '104.198.40.11',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 2',
            used: '1T',
            volume: 'Vol3',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 3',
            used: '2T',
            volume: 'Vol4',
            created: '4:10PM 3/14/17',
          },
        ],
      },
      {
        id: 2,
        state: 'Activated',
        name: 'HostnameTwo',
        ip: '104.198.15.51',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 2',
            used: '1T',
            volume: 'Vol3',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 3',
            used: '2T',
            volume: 'Vol4',
            created: '4:10PM 3/14/17',
          },
        ],
      },
      {
        id: 3,
        state: 'Activated',
        name: 'HostnameThree',
        ip: '104.198.43.13',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 2',
            used: '1T',
            volume: 'Vol3',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 3',
            used: '2T',
            volume: 'Vol4',
            created: '4:10PM 3/14/17',
          },
        ],
      },
      {
        id: 4,
        state: 'Activated',
        name: 'HostnameFour',
        ip: '104.198.42.42',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
        ],
      },
      {
        id: 5,
        state: 'Activated',
        name: 'HostnameFive',
        ip: '104.198.76.115',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 3',
            used: '2T',
            volume: 'Vol4',
            created: '4:10PM 3/14/17',
          },
        ],
      },
    ],
  },
  'GET /v1/dashboard': {
    numbers: [
      {
        icon: 'laptop',
        color: '#64ea91',
        title: 'Hosts',
        number: 5,
      }, {
        icon: 'hdd',
        color: '#8fc9fb',
        title: 'Disks',
        number: 25,
      }, {
        icon: 'database',
        color: '#d897eb',
        title: 'Volumes',
        number: 114,
      }, {
        icon: 'camera-o',
        color: '#f69899',
        title: 'Snapshots',
        number: 46,
      },
    ],
  },
  'GET /v1/volumes': { "createTypes": { "volume": "http://54.223.25.181:9500/v1/volumes" }, "data": [{ "actions": { "attach": "http://54.223.25.181:9500/v1/volumes/logan?action=attach" }, "id": "logan", "links": { "self": "http://54.223.25.181:9500/v1/volumes/logan" }, "longhornImage": "rancher/longhorn:latest", "name": "logan", "numberOfReplicas": 2, "replicas": [{ "address": "172.17.0.7", "hostId": "d7c419e3-ae14-4115-a060-3f201395a17b", "name": "logan-replica-6b52250d-4e44-40ca", "running": true }, { "address": "172.17.0.2", "hostId": "d7c419e3-ae14-4115-a060-3f201395a17b", "name": "logan-replica-dbfaa09a-dd07-4762", "running": true }], "size": "10737418240", "staleReplicaTimeout": 20, "state": "detached", "type": "volume" }], "links": { "self": "http://54.223.25.181:9500/v1/volumes" }, "resourceType": "volume", "type": "collection" }
};
