export default {
  'GET /v1/backup': {
    type: 'collection',
    data: [
      {
        id: 'BackupID1',
        snapshot: 'Snapshot1',
        timestamp: '11:06AM 3/24/2017',
        size: '500GB',
        created: '4:10PM 3/14/17',
      },
      {
        id: 'BackupID2',
        snapshot: 'Snapshot2',
        timestamp: '11:06AM 3/24/2017',
        size: '500GB',
        created: '4:10PM 3/14/17',
      },
      {
        id: 'BackupID3',
        snapshot: 'Snapshot3',
        timestamp: '11:06AM 3/24/2017',
        size: '500GB',
        created: '4:10PM 3/14/17',
      },
      {
        id: 'BackupID4',
        snapshot: 'Snapshot4',
        timestamp: '11:06AM 3/24/2017',
        size: '500GB',
        created: '4:10PM 3/14/17',
      },
    ],
  },
  'GET /v1/host': {
    type: 'collection',
    data: [
      {
        id: 1,
        state: 'Activated',
        name: 'HostnameOne',
        ip: '104.198.40.11',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 2',
            used: '1T',
            volume: 'Vol3',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 3',
            used: '2T',
            volume: 'Vol4',
            created: '4:10PM 3/14/17',
          },
        ],
      },
      {
        id: 2,
        state: 'Activated',
        name: 'HostnameTwo',
        ip: '104.198.15.51',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 2',
            used: '1T',
            volume: 'Vol3',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 3',
            used: '2T',
            volume: 'Vol4',
            created: '4:10PM 3/14/17',
          },
        ],
      },
      {
        id: 3,
        state: 'Activated',
        name: 'HostnameThree',
        ip: '104.198.43.13',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 2',
            used: '1T',
            volume: 'Vol3',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 3',
            used: '2T',
            volume: 'Vol4',
            created: '4:10PM 3/14/17',
          },
        ],
      },
      {
        id: 4,
        state: 'Activated',
        name: 'HostnameFour',
        ip: '104.198.42.42',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
        ],
      },
      {
        id: 5,
        state: 'Activated',
        name: 'HostnameFive',
        ip: '104.198.76.115',
        total: '2T',
        used: '61G',
        replicas: [
          {
            status: 'Healthy',
            name: 'Replica 1',
            used: '61GB',
            volume: 'Vol2',
            created: '4:10PM 3/14/17',
          },
          {
            status: 'Healthy',
            name: 'Replica 3',
            used: '2T',
            volume: 'Vol4',
            created: '4:10PM 3/14/17',
          },
        ],
      },
    ],
  },
  'GET /v1/dashboard': {
    numbers: [
      {
        icon: 'laptop',
        color: '#64ea91',
        title: 'Hosts',
        number: 5,
      }, {
        icon: 'hdd',
        color: '#8fc9fb',
        title: 'Disks',
        number: 25,
      }, {
        icon: 'database',
        color: '#d897eb',
        title: 'Volumes',
        number: 114,
      }, {
        icon: 'camera-o',
        color: '#f69899',
        title: 'Snapshots',
        number: 46,
      },
    ],
  },
  'GET /v1/volumes': {
    type: 'collection',
    resourceType: 'volume',
    links: {
      self: '…/v1/volumes',
    },
    actions: {},
    data: [
      {
        id: 'vol1',
        type: 'volume',
        links: {
          self: '…/v1/volumes/vol1',
          backups: '…/v1/volumes/vol1/backups',
          snapshots: '…/v1/volumes/vol1/snapshots',
          recurrings: '…/v1/volumes/vol1/recurrings',
        },
        actions: {
          attach: '…/v1/volumes/vol1/?action=attach',
          detach: '…/v1/volumes/vol1/?action=detach',
        },
        controller: {
          id: '1i69',
          hostId: '39e1f6b7-8ea7-4987-ba57-13e1fc89c815',
          address: 'http://controller.volume-vol1.rancher.internal:9501',
          running: true,
        },
        replicas: [
          {
            id: '1i82',
            used: '61GB',
            hostId: 'HostnameOne',
            address: 'tcp://replica-5a0e1172-afb5-47fa.rancher.internal:9502',
            running: true,
            mode: 'RW',
            name: 'replica-5a0e1172-afb5-47fa',
            created: '2017-03-21T01:13:58Z',
          },
          {
            id: '1i81',
            used: '1G',
            hostId: 'HostnameOne',
            address: 'tcp://replica-78373bce-8954-49cb.rancher.internal:9502',
            running: true,
            mode: 'ERR',
            badTimestamp: '2017-02-28T02:43:19Z',
            name: 'replica-78373bce-8954-49cb',
            created: '2017-03-21T01:13:58Z',
          },
        ],
        status: 'Attached',
        created: '2017-03-21T01:13:58Z',
        hostId: 'HostnameOne',
        externalId: 'container-test',
        frontEnd: '/dev/longhorn/vol1',
        size: 429496729600,
        used: 23580672,
        numberOfReplicas: 2,
        staleReplicaTimeout: 24,
      },
      {
        id: 'vol2',
        type: 'volume',
        links: {
          self: '…/v1/volumes/vol1',
          backups: '…/v1/volumes/vol1/backups',
          snapshots: '…/v1/volumes/vol1/snapshots',
          recurrings: '…/v1/volumes/vol1/recurrings',
        },
        actions: {
          attach: '…/v1/volumes/vol1/?action=attach',
          detach: '…/v1/volumes/vol1/?action=detach',
        },
        controller: {
          id: '1i69',
          hostId: '39e1f6b7-8ea7-4987-ba57-13e1fc89c815',
          address: 'http://controller.volume-vol1.rancher.internal:9501',
          running: true,
        },
        replicas: [
          {
            id: '1i82',
            used: '61GB',
            hostId: 'HostnameOne',
            address: 'tcp://replica-5a0e1172-afb5-47fa.rancher.internal:9502',
            running: true,
            mode: 'RW',
            name: 'replica-5a0e1172-afb5-47fa',
            created: '2017-03-21T01:13:58Z',
          },
          {
            id: '1i81',
            used: '61GB',
            hostId: 'HostnameOne',
            address: 'tcp://replica-78373bce-8954-49cb.rancher.internal:9502',
            running: true,
            mode: 'ERR',
            badTimestamp: '2017-02-28T02:43:19Z',
            name: 'replica-78373bce-8954-49cb',
            created: '2017-03-21T01:13:58Z',
          },
        ],
        status: 'Attached',
        created: '2017-03-21T01:13:58Z',
        hostId: 'HostnameTwo',
        externalId: 'container-test',
        frontEnd: '/dev/longhorn/vol1',
        size: 429496729600,
        used: 23580672,
        numberOfReplicas: 2,
        staleReplicaTimeout: 24,
      },
    ],
  }
};
