name: build
on:
  push:
    branches:
    - master
    - v*
    tags:
    - v*
jobs:
  build_push_image:
    name: Build and push image
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/') }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # For multi-platform support
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Declare branch
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_ENV"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # longhornio/longhorn-ui image
    - name: docker-publish
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: longhornio/longhorn-ui:${{ env.branch }}-head
        file: Dockerfile
        sbom: true
        build-args: |
          VERSION=${{ env.sha_short }}

    - name: docker-publish-with-tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: longhornio/longhorn-ui:${{ github.ref_name }}
        file: Dockerfile
        sbom: true
        build-args: |
          VERSION=${{ github.ref_name }}
